dist: focal
language: node_js
node_js:
  - 18
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  fqdn: prabaha.in
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$